spring:
  h2:
    console:
      enabled: true
      path: /h2  # Context path
  datasource:
    url: jdbc:h2:mem:test  # JDBC URL
  jpa:
    hibernate:
      ddl-auto: create  # 스키마 자동 생성
    show-sql: true  # SQL 쿼리 출력
server:
  servlet:
    encoding:
      force-response: true
mail:
  address:
    admin: admin@email.com
jwt:
  key: ${JWT_SECRET_KEY} # ${JWT_KEY}
  access-token-expiration-minutes: 30  # minutes
  refresh-token-expiration-minutes: 420